
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dldajrxpktlvdjzteuhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZGFqcnhwa3RsdmRqenRldWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTY0OTMsImV4cCI6MjA1OTI3MjQ5M30.ez0zBNMFI_N8ovb1A2mfW_K6jpz1e-jHwr32pK00H4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Log when the client is initialized
console.log('Supabase client initialized with URL:', SUPABASE_URL);
