// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmywdrwjdqmrkafhiuwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteXdkcndqZHFtcmthZmhpdXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTcyNzIsImV4cCI6MjA2MDI3MzI3Mn0.5FDdsLqE8Tgb1KFphJRbjg65CFsYUzcxt_l7xMRgT0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);